#! /usr/bin/env python2.7
# -*- coding: utf-8 -*-

import sys
from lexer import *
from parser import *
from AST import output

data = open(sys.argv[1])
data = data.read()

lexer.input(data)

while True:    
    tok = lexer.token()
    if not tok: break

parser = yacc.yacc()

kilo = None
print kilo

arbol = parser.parse(data)
tabs = 0
for i in reversed(output):
	if i[0] == "BLOCK":
		tabs += 1
	for j in i:
		print tabs*"\t"+j
	