#! /usr/bin/env python2.7
# -*- coding: utf-8 -*-

import  sys
from    lexer  import *
from    parser import *

if len(sys.argv) == 1:
    print "ERROR: Debe introducir el nombre de un archivo."
    exit(1)
elif len(sys.argv) > 2:
    print "ERROR: Número inválido de argumentos."
    exit(1)

try:
    data = open(sys.argv[1])
except:
    print "ERROR: El archivo '%s' no existe." % (sys.argv[1])
    exit(1)

data = data.read()

lexer.input(data)
while True:    
    tok = lexer.token()
    if not tok: break

if lexError != []:
    for error in lexError:
        print error
    exit(1)
else:
    arbol = parser.parse(data)
    if yaccError != []:
        print yaccError[0]
    else:
        print arbol.printTree(0)
